FROM python:3.11-slim

RUN apt-get update \
    && apt-get -y install libpq-dev gcc \
    && pip install psycopg2

RUN mkdir /tg_bot

WORKDIR /tg_bot

COPY requirements.txt .

RUN pip install -r requirements.txt

CMD ["python", "/bot.py"]